changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"
  - "**/*.story.{js,ts,tsx}"
  - "**/*.stories.{js,ts,tsx}"
  - javascript/webapp/**/*

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/react-hooks@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@fluentui/react@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
      "@types/react-dom":
        optional: true
      react-dom:
        optional: true
  "@fluentui/style-utilities@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react":
        optional: true
  "@monaco-editor/react@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "@storybook/addon-controls@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      webpack: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      "@storybook/react-webpack5": "*"
      webpack: "*"
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      webpack:
        optional: true
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      webpack: "*"
    peerDependenciesMeta:
      "@storybook/react-webpack5":
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true
  "@storybook/addon-interactions@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      webpack: "*"
  "@storybook/addons@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/blocks@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/builder-manager@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/builder-webpack5@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/cli@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/core-common@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      webpack: ">= 5"
    peerDependenciesMeta:
      "@storybook/react-webpack5":
        optional: true
      webpack:
        optional: true
  "@storybook/core-server@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/core-webpack@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      react: "*"
      react-dom: "*"
  "@storybook/instrumenter@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/preset-react-webpack@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/react-webpack5@*":
    peerDependencies:
      webpack: "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/store@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@thematic/fluent@*":
    peerDependencies:
      react-dom: "*"
  allotment@*:
    peerDependenciesMeta:
      react-dom:
        optional: true
  observable-hooks@*:
    peerDependenciesMeta:
      react-dom:
        optional: true
  path-equal@*:
    dependencies:
      tslib: "*"
  react-router-dom@*:
    peerDependenciesMeta:
      react-dom:
        optional: true
  storybook@*:
    peerDependencies:
      "@storybook/react-webpack5": "*"
  styled-components@*:
    dependencies:
      react-is: ^16
    peerDependenciesMeta:
      react-dom:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
