changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
  "@uifabric/icons@*":
    peerDependencies:
      react: "*"
  "@uifabric/styling@*":
    peerDependencies:
      "@types/react-dom": "*"
      react: "*"
      react-dom: "*"
  path-equal@*:
    dependencies:
      tslib: "*"
  react-router-dom@*:
    dependencies:
      "@remix-run/router": ^1.0.0
  styled-components@*:
    dependencies:
      react-is: ^16

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
